export const STUDENTS = [
  { id: 's1', name: 'Abdullah Alwi Hafidh', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's2', name: 'Adelina Elsandra Mackayla Putri', handle: 'adelina.elsandraa', program: 'Informatika', year: 2022, avatar: '/card/Adelina Elsandra Mackayla Putri.png', motto: 'Ketika hidup memberimu tantangan, terimalah dengan senyuman dan sedikit tawa.' },
  { id: 's3', name: 'Ahmad Dhiyaul Haq', handle: 'aahaqii', program: 'Informatika', year: 2024, avatar: '/card/Ahmad Dhiyaul Haq.png', motto: 'Meneng, Ngaleh, Menang' },
  { id: 's4', name: 'Ahmad Ubaydillah', handle: 'bydllah_', program: 'Informatika', year: 2023, avatar: '/card/Ahmad Ubaydillah.png', motto: 'Hal-hal baik tidak bertahan selamanya dan hidup berjalan begitu cepat.' },
  { id: 's5', name: 'Almaziidah Rihhadatul Aisya', handle: 'zeeayayaw', program: 'Informatika', year: 2021, avatar: '/card/Almaziidah Rihhadatul Aisya.png', motto: 'Slow, not stuck' },
  { id: 's6', name: 'Ananda Muhammad Raihan', handle: 'Raiizannn', program: 'Informatika', year: 2024, avatar: '/card/Ananda Muhammad Raihan.png', motto: 'covs' },
  { id: 's7', name: 'Andini Dwi Rismayani', handle: 'andinidwwi', program: 'Informatika', year: 2024, avatar: '/card/Andini Dwi Rismayani.png', motto: 'honda scoopy' },
  { id: 's8', name: 'Andreano Jeremi Saragih', handle: 'andresaragih_06', program: 'Informatika', year: 2023, avatar: '/card/Andreano Jeremi Saragih.png', motto:'Yakobus 1:12 menyatakan bahwa orang yang bertahan dalam pencobaan akan berbahagia, karena setelah teruji, ia akan menerima mahkota kehidupan yang dijanjikan Allah kepada mereka yang mengasihi-Nya' },
  { id: 's9', name: 'Ardindha Ramadhani', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's10', name: 'Bramantyo Bagas Pratomo', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's11', name: 'Chandra Mahendra Alam Pramudita', handle: 'caanmhndra ', program: 'Informatika', year: 2023, avatar: '/card/Chandra Mahendra Alam Pramudita.png', motto:'Jalanin saja, nanti juga selesai' },
  { id: 's12', name: 'Chello Mitha Saskia Bella', handle: 'chello_cel', program: 'Informatika', year: 2023, avatar: '/card/Chello Mitha Saskia Bella.png', motto:'Kesuksesan dimulai ketika kamu berani mencoba, meski belum tentu langsung sempurna. -Soichiro Honda' },
  { id: 's13', name: 'Dinda Auliaul Qibtiyah', handle: 'dndaaulyaa._', program: 'Informatika', year: 2023, avatar: '/card/Dinda Auliaul Qibtiyah.png', motto:'Impian besar membutuhkan langkah kecil yang gigih' },
  { id: 's14', name: 'Farel Surya Pradiska', handle: 'frl.sry', program: 'Informatika', year: 2023, avatar: '/card/Farel Surya Pradiska.png', motto:'Bergerak pelan lebih baik daripada diam.' },
  { id: 's15', name: "Farisha Na'ila Zahronissa", handle: 'hy.nssa', program: 'Informatika', year: 2023, avatar: "/card/Farisha Na'ila Zahronissa.png", motto:'Setiap langkah keluar dari zona nyaman adalah langkah menuju versi terbaikku' },
  { id: 's16', name: 'Jafar Sodiq', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's17', name: 'Kawan Nainggolan', handle: 'kawan_nainggolan05', program: 'Informatika', year: 2023, avatar: '/card/Kawan Nainggolan.png', motto:'Life is Roblox' },
  { id: 's18', name: 'Keisya Avrilia Humaira Chumaini', handle: 'syaa.assa', program: 'Informatika', year: 2023, avatar: '/card/Keisya Avrilia Humaira Chumaini.png', motto:'Maju tak gentar mundur tak ganjel ' },
  { id: 's19', name: 'Krisna Rafif Daffa Amrullah', handle: 'krsrffam', program: 'Informatika', year: 2023, avatar: '/card/Krisna Rafif Daffa Amrullah.png', motto:'Tetap lah semangat karena ada ayam geprek yang selalu menemani setiap hari ' },
  { id: 's20', name: 'Lukman Zuhdi Athallah', handle: 'Overt.athalah', program: 'Informatika', year: 2023, avatar: '/card/Lukman Zuhdi Athallah.png', motto:'Ws a gak usah kepo' },
  { id: 's21', name: 'M Faisal Afdani', handle: 'afdani_faisal', program: 'Informatika', year: 2023, avatar: '/card/M Faisal Afdani.png', motto:'GAS TERUSS' },
  { id: 's22', name: 'M. Aliefta Rizky Alvansyah', handle: 'alvan.mar360_', program: 'Informatika', year: 2023, avatar: '/card/M. Aliefta Rizky Alvansyah.png', motto:'Jadikan diri lebih baik dari hari kemarin' },
  { id: 's23', name: 'Mochamad Rifki Al Farizi', handle: '_dheayissmm', program: 'Informatika', year: 2023, avatar: '/card/Mochamad Rifki Al Farizi.png', motto:'Makan agar hidup dan hidup untuk cari makan' },
  { id: 's24', name: 'Mohammad Rifqi Abrar Rabbani', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's25', name: 'Muhammad Ahzar Fahrezi', handle: 'aliesy._.sc', program: 'Informatika', year: 2023, avatar: '/card/Muhammad Ahzar Fahrezi.png', motto:'Teruslah melangkah, selangkah demi selangkah' },
  { id: 's26', name: 'Muhammad Berlin Meimumtazy', handle: 'berlinmm_', program: 'Informatika', year: 2023, avatar: '/card/Muhammad Berlin Meimumtazy.png', motto:'Jangan ragu untuk mencoba, karena tanpa mencoba kita tidak pernah tau hasilnya' },
  { id: 's27', name: 'Muhammad Fata Azzaki', handle: 'muhmmmdzy', program: 'Informatika', year: 2023, avatar: '/card/Muhammad Fata Azzaki.png', motto:'Muda berkarya, tua bermakna.' },
  { id: 's28', name: 'Muhammad Hikamul Auliya', handle: 'hikamml', program: 'Informatika', year: 2023, avatar: '/card/Muhammad Hikamul Auliya.png', motto:'Tidak ada jalan tanpa debu, Dan tidak ada kesuksesan tanpa doa ibu' },
  { id: 's29', name: 'Muhammad Rendra Basyori', handle: 'rendra_basyori', program: 'Informatika', year: 2023, avatar: '/card/Muhammad Rendra Basyori.png', motto:'Sekreatif Apapun Kata-kata Motivasi, Tidak Akan Bisa Merubah Diri Jika Hanya Diam Tanpa Sebuah Aksi' },
  { id: 's30', name: 'Muhammad Revaldo Pratama', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's31', name: 'Muhammad Risky Gucie Perera', handle: 'gu.ccccc', program: 'Informatika', year: 2023, avatar: '/card/Muhammad Risky Gucie Perera.png', motto:'semak belukar pasti ada hal yang indah dibaliknya' },
  { id: 's32', name: 'Muhammad Safarudin Firmani', handle: 'zanalarsen_', program: 'Informatika', year: 2023, avatar: '/card/Muhammad Safarudin Firmani.png', motto:'LAGI ASIK NGODING MALAH DISURUH TIDUR' },
  { id: 's33', name: 'Naufal Zaidan Ardzi', handle: 'naufalarzii', program: 'Informatika', year: 2023, avatar: '/card/Naufal Zaidan Ardzi.png', motto:'iyya' },
  { id: 's34', name: 'Nawaf Ariq Hilalbi', handle: 'qiraayyy', program: 'Informatika', year: 2023, avatar: '/card/ariq.png', motto:'Boleh jadi kamu membenci sesuatu, padahal itu baik bagimu dan boleh jadi kamu menyukai sesuatu, padahal itu buruk bagimu.' },
  { id: 's35', name: 'Noval Gesit Mustofa', handle: 'palogic.id', program: 'Informatika', year: 2023, avatar: '/card/Noval Gesit Mustofa.png', motto:'Tidak ada yang tidak bisa, Cari passion luh! ' },
  { id: 's36', name: 'Raden Bagus Rizqiawan', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's37', name: 'Raditya Arva Messi Jagaddhita', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's38', name: 'Rendy Alfiansyah', handle: 'rendyy_alfiansyahh ', program: 'Informatika', year: 2023, avatar: '/card/Rendy Alfiansyah.png', motto:'Veni, Vidi, Vici' },
  { id: 's39', name: 'Reynata Mahessa Mulia Efendi', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's40', name: 'Rifdatun Nailah Mafaza', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's41', name: 'Rifki Hidayatullah Setyono', handle: 'ripkiii.hs', program: 'Informatika', year: 2023, avatar: '/card/Rifki Hidayatullah Setyono.png', motto:'jangan pernah berhenti belajar' },
  { id: 's42', name: 'Rifky Tirta Zakaria', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's43', name: 'Rifqi Muhamad Rosadi', handle: 'iqq.exe', program: 'Informatika', year: 2023, avatar: '/card/Rifqi Muhamad Rosadi.png', motto:'Lagi invest leher keatas' },
  { id: 's44', name: 'Rio Al Kaseno', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's45', name: 'Riva Muchlas Zia Arkazori', handle: 'rvazkri', program: 'Informatika', year: 2023, avatar: '/card/Riva Muchlas Zia Arkazori.png', motto:'Tidak perlu malu untuk menangis, sebab air mata merupakan saksi dari keberanian manusia yang paling besar. Keberanian untuk menderita. - Viktor E. Frankl' },
  { id: 's46', name: 'Rojana Natalia Abisay', handle: 'natalia_abisay', program: 'Informatika', year: 2023, avatar: '/card/Rojana Natalia Abisay.png', motto:'Berani Melangkah Kecil,Besar di Masa Depan' },
  { id: 's47', name: 'Salama Sandi Haq', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's48', name: 'Siti Amelia Istiqomah', handle: 'amliaistqmh_', program: 'Informatika', year: 2023, avatar: '/card/Siti Amelia Istiqomah.png', motto:'Kegagalan Adalah Langkah Awal Untuk Menuju Kesuksesan ' },
  { id: 's49', name: 'Stephani Chris Anna', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's50', name: 'Syafa Humairoh Sofyani', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's51', name: 'Tegar Adidtya Pratama', handle: 'adidtyapr', program: 'Informatika', year: 2023, avatar: '/card/Tegar Adidtya Pratama.png', motto:'“Berpikir sistematis, memimpin dengan logika, dan menginspirasi dengan empati.”' },
  { id: 's52', name: 'Teti Ina Pangaribuan', handle: '', program: 'Informatika', year: 2023, avatar: '/card/', motto:null },
  { id: 's53', name: 'Villiniu Adika Khrisna Priwanto', handle: 'niuprime', program: 'Informatika', year: 2023, avatar: '/card/', motto:'With Great Power Comes Great Responsibility' },
  { id: 's54', name: 'Wafa Aidan Nizzar Ghaisani', handle: 'wafa.aidan', program: 'Informatika', year: 2023, avatar: '/card/Wafa Aidan Nizzar Ghaisani.png', motto:'Through Passion, I Gain Focus' },
  { id: 's55', name: 'Ziqra Muhammad Albani', handle: 'zqraal_', program: 'Informatika', year: 2023, avatar: '/card/Ziqra Muhammad Albani.png', motto:'Moto tuh bukannya kendaraan roda dua? xixixi' },

]
