export const STUDENTS = [
  { id: 's1', name: 'Abdullah Alwi Hafidh', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's2', name: 'Adelina Elsandra Mackayla Putri', handle: 'adelina.elsandraa', program: 'Informatika', year: 2022, avatar: '/card/Adelina Elsandra Mackayla Putri.png', motto: 'Ketika hidup memberimu tantangan, terimalah dengan senyuman dan sedikit tawa.' },
  { id: 's3', name: 'Ahmad Dhiyaul Haq', handle: 'budi', program: 'Informatika', year: 2024, avatar: '/avatar/budi.jpg', motto: 'Kode bersih, solusi tepat.' },
  { id: 's4', name: 'Ahmad Ubaydillah', handle: 'dewi', program: 'Informatika', year: 2023, avatar: '/avatar/dewi.jpg', motto: 'Kolaborasi mengalahkan egoku.' },
  { id: 's5', name: 'Almaziidah Rihhadatul Aisya', handle: 'eko', program: 'Informatika', year: 2021, avatar: '/avatar/eko.jpg', motto: 'Dari ide menjadi produk.' },
  { id: 's6', name: 'Ananda Muhammad Raihan', handle: 'fitri', program: 'Informatika', year: 2024, avatar: '/avatar/fitri.jpg', motto: 'Jangan takut gagal, takutlah saat tidak mencoba.' },
  { id: 's7', name: 'Andini Dwi Rismayani', handle: 'fitri', program: 'Informatika', year: 2024, avatar: '/avatar/fitri.jpg', motto: 'Satu baris kode, satu langkah maju.' },
  { id: 's8', name: 'Andreano Jeremi Saragih', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's9', name: 'Ardindha Ramadhani', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's10', name: 'Bramantyo Bagas Pratomo', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's11', name: 'Chandra Mahendra Alam Pramudita', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's12', name: 'Chello Mitha Saskia Bella', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's13', name: 'Dinda Auliaul Qibtiyah', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's14', name: 'Farel Surya Pradiska', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's15', name: "Farisha Na'ila Zahronissa", handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's16', name: 'Jafar Sodiq', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's17', name: 'Kawan Nainggolan', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's18', name: 'Keisya Avrilia Humaira Chumaini', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's19', name: 'Krisna Rafif Daffa Amrullah', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's20', name: 'Lukman Zuhdi Athallah', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's21', name: 'M Faisal Afdani', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's22', name: 'M. Aliefta Rizky Alvansyah', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's23', name: 'Mochamad Rifki Al Farizi', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's24', name: 'Mohammad Rifqi Abrar Rabbani', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's25', name: 'Muhammad Ahzar Fahrezi', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's26', name: 'Muhammad Berlin Meimumtazy', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's27', name: 'Muhammad Fata Azzaki', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's28', name: 'Muhammad Hikamul Auliya', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's29', name: 'Muhammad Rendra Basyori', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's30', name: 'Muhammad Revaldo Pratama', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's31', name: 'Muhammad Risky Gucie Perera', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's32', name: 'Muhammad Safarudin Firmani', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's33', name: 'Naufal Zaidan Ardzi', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's34', name: 'Nawaf Ariq Hilalbi', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's35', name: 'Noval Gesit Mustofa', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's36', name: 'Raden Bagus Rizqiawan', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's37', name: 'Raditya Arva Messi Jagaddhita', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's38', name: 'Rendy Alfiansyah', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's39', name: 'Reynata Mahessa Mulia Efendi', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's40', name: 'Rifdatun Nailah Mafaza', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's41', name: 'Rifki Hidayatullah Setyono', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's42', name: 'Rifky Tirta Zakaria', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's43', name: 'Rifqi Muhamad Rosadi', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's44', name: 'Rio Al Kaseno', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's45', name: 'Riva Muchlas Zia Arkazori', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's46', name: 'Rojana Natalia Abisay', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's47', name: 'Salama Sandi Haq', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's48', name: 'Siti Amelia Istiqomah', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's49', name: 'Stephani Chris Anna', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's50', name: 'Syafa Humairoh Sofyani', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's51', name: 'Tegar Adidtya Pratama', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's52', name: 'Teti Ina Pangaribuan', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's53', name: 'Villiniu Adika Khrisna Priwanto', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's54', name: 'Wafa Aidan Nizzar Ghaisani', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },
  { id: 's55', name: 'Ziqra Muhammad Albani', handle: '', program: 'Informatika', year: 2023, avatar: null, motto:null },

]
